#!/bin/bash
set -e

OLPC_OS_BUILD=build-10.2_xo1.5-108
OLPC_OS_KERNEL=2.6.31_xo1.5-20100108.1640.1.olpc.846ed3a
DEVICE=/dev/disk/by-id/usb-DSE_Micro_Drive_0000000000002F-0:0-part1

CACHE=yes
while [ ! -z "${1}" ]; do
    case "${1}" in
	--no-cache)
	    shift
	    CACHE=no
	    ;;
	--help)
	    shift
	    echo "--no-cache"
	    exit 0
	    ;;
	*)
	    DEVICE=${1}
	    shift
	    if [ ! -e ${DEVICE} ]; then
		echo "build: no such device ${DEVICE}"
		exit 1
	    fi
    esac

done

mkdir -p cache
mkdir -p cache/boot
mkdir -p cache/lib/modules
mkdir -p cache/lib/firmware

if [ $CACHE = no -o ! -e cache/tinycore.gz ]; then
    rsync --archive --checksum rsync://distro.ibiblio.org/distros/tinycorelinux/2.x/release/distribution_files/tinycore.gz cache/
fi

if [ $CACHE = no -o ! -e cache/boot/vmlinuz-${OLPC_OS_KERNEL} ]; then
    rsync --archive --checksum rsync://updates.laptop.org/${OLPC_OS_BUILD}/root/boot/vmlinuz-${OLPC_OS_KERNEL} cache/boot/
fi

if [ $CACHE = no -o ! -e cache/lib/modules/${OLPC_OS_KERNEL} ]; then
    rsync --archive --checksum rsync://updates.laptop.org/${OLPC_OS_BUILD}/root/lib/modules/${OLPC_OS_KERNEL} cache/lib/modules/
fi

if [ $CACHE = no -o ! -e cache/lib/firmware/sd8686.bin ]; then
    rsync --archive --checksum rsync://updates.laptop.org/${OLPC_OS_BUILD}/root/lib/firmware/sd8686* cache/lib/firmware/
fi

echo "build: repack tree"
TREE=/tmp/tinycore.tree.$$
mkdir -p ${TREE}
zcat cache/tinycore.gz | \
(cd ${TREE} && cpio --extract --make-directories --quiet)
rm -rf ${TREE}/lib/modules/2.6.29.1-tinycore
cp -pr cache/lib/modules/${OLPC_OS_KERNEL} ${TREE}/lib/modules/
cp -pr cache/lib/firmware ${TREE}/lib/
(cd ${TREE} && (find | cpio -o -H newc --quiet | gzip -2 > ../tinycore.new.gz) )
rm -rf ${TREE}

echo "build: create output"
rm -rf output
mkdir -p output
mkdir -p output/boot

cp cache/tinycore.new.gz output/boot/tinycore.gz
cp cache/boot/vmlinuz-${OLPC_OS_KERNEL} output/boot/vmlinuz

cat << EOF > output/boot/olpc.fth
\ olpc.fth

setup-smbios
unfreeze
dcon-unfreeze
visible

\ announce self
.( -- OpenFirmware Tiny Core Linux boot script, quozl@laptop.org, 2010-01-25 -- ) cr cr

" fbcon=font:SUN12x22 superuser quiet time opt=/dev/sda1" to boot-file
" u:\boot\vmlinuz" to boot-device
" u:\boot\tinycore.gz" to ramdisk

boot
EOF

# setup wireless
mkdir output/opt
cat <<EOF > output/opt/bootlocal.sh
#!/bin/sh
LD_LIBRARY_PATH=/lib:/opt iwconfig eth0 essid quozl.linux.org.au
EOF
chmod +x output/opt/bootlocal.sh
cp /sbin/iwconfig /lib/libiw.so.29 output/opt/

# copy to media
echo "build: copy to media"
mke2fs -q ${DEVICE}
mount ${DEVICE} /mnt
rsync --archive output/boot output/opt /mnt/
umount /mnt/
